//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceUI.WCFCarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCarService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddClient", ReplyAction="http://tempuri.org/IService/AddClientResponse")]
        void AddClient(ProjectCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddClient", ReplyAction="http://tempuri.org/IService/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(ProjectCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddAuto", ReplyAction="http://tempuri.org/IService/AddAutoResponse")]
        void AddAuto(ProjectCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddAuto", ReplyAction="http://tempuri.org/IService/AddAutoResponse")]
        System.Threading.Tasks.Task AddAutoAsync(ProjectCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddComanda", ReplyAction="http://tempuri.org/IService/AddComandaResponse")]
        void AddComanda(ProjectCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddComanda", ReplyAction="http://tempuri.org/IService/AddComandaResponse")]
        System.Threading.Tasks.Task AddComandaAsync(ProjectCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDetaliuComanda", ReplyAction="http://tempuri.org/IService/AddDetaliuComandaResponse")]
        void AddDetaliuComanda(ProjectCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDetaliuComanda", ReplyAction="http://tempuri.org/IService/AddDetaliuComandaResponse")]
        System.Threading.Tasks.Task AddDetaliuComandaAsync(ProjectCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddImage", ReplyAction="http://tempuri.org/IService/AddImageResponse")]
        void AddImage(ProjectCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddImage", ReplyAction="http://tempuri.org/IService/AddImageResponse")]
        System.Threading.Tasks.Task AddImageAsync(ProjectCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMaterial", ReplyAction="http://tempuri.org/IService/AddMaterialResponse")]
        void AddMaterial(ProjectCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMaterial", ReplyAction="http://tempuri.org/IService/AddMaterialResponse")]
        System.Threading.Tasks.Task AddMaterialAsync(ProjectCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMecanic", ReplyAction="http://tempuri.org/IService/AddMecanicResponse")]
        void AddMecanic(ProjectCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMecanic", ReplyAction="http://tempuri.org/IService/AddMecanicResponse")]
        System.Threading.Tasks.Task AddMecanicAsync(ProjectCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddOperatie", ReplyAction="http://tempuri.org/IService/AddOperatieResponse")]
        void AddOperatie(ProjectCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddOperatie", ReplyAction="http://tempuri.org/IService/AddOperatieResponse")]
        System.Threading.Tasks.Task AddOperatieAsync(ProjectCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSasiu", ReplyAction="http://tempuri.org/IService/AddSasiuResponse")]
        void AddSasiu(ProjectCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSasiu", ReplyAction="http://tempuri.org/IService/AddSasiuResponse")]
        System.Threading.Tasks.Task AddSasiuAsync(ProjectCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuto", ReplyAction="http://tempuri.org/IService/GetAllAutoResponse")]
        ProjectCarService.Auto[] GetAllAuto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuto", ReplyAction="http://tempuri.org/IService/GetAllAutoResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Auto[]> GetAllAutoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAutoByClientId", ReplyAction="http://tempuri.org/IService/GetAutoByClientIdResponse")]
        ProjectCarService.Auto[] GetAutoByClientId(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAutoByClientId", ReplyAction="http://tempuri.org/IService/GetAutoByClientIdResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Auto[]> GetAutoByClientIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClients", ReplyAction="http://tempuri.org/IService/GetAllClientsResponse")]
        ProjectCarService.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClients", ReplyAction="http://tempuri.org/IService/GetAllClientsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllComands", ReplyAction="http://tempuri.org/IService/GetAllComandsResponse")]
        ProjectCarService.Comanda[] GetAllComands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllComands", ReplyAction="http://tempuri.org/IService/GetAllComandsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Comanda[]> GetAllComandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMaterials", ReplyAction="http://tempuri.org/IService/GetAllMaterialsResponse")]
        ProjectCarService.Material[] GetAllMaterials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMaterials", ReplyAction="http://tempuri.org/IService/GetAllMaterialsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Material[]> GetAllMaterialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMecanics", ReplyAction="http://tempuri.org/IService/GetAllMecanicsResponse")]
        ProjectCarService.Mecanic[] GetAllMecanics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMecanics", ReplyAction="http://tempuri.org/IService/GetAllMecanicsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Mecanic[]> GetAllMecanicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDetailsCommands", ReplyAction="http://tempuri.org/IService/GetAllDetailsCommandsResponse")]
        ProjectCarService.DetaliuComanda[] GetAllDetailsCommands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDetailsCommands", ReplyAction="http://tempuri.org/IService/GetAllDetailsCommandsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.DetaliuComanda[]> GetAllDetailsCommandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllImagies", ReplyAction="http://tempuri.org/IService/GetAllImagiesResponse")]
        ProjectCarService.Imagine[] GetAllImagies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllImagies", ReplyAction="http://tempuri.org/IService/GetAllImagiesResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Imagine[]> GetAllImagiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperations", ReplyAction="http://tempuri.org/IService/GetOperationsResponse")]
        ProjectCarService.Operatie[] GetOperations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperations", ReplyAction="http://tempuri.org/IService/GetOperationsResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Operatie[]> GetOperationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllChassis", ReplyAction="http://tempuri.org/IService/GetAllChassisResponse")]
        ProjectCarService.Sasiu[] GetAllChassis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllChassis", ReplyAction="http://tempuri.org/IService/GetAllChassisResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Sasiu[]> GetAllChassisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiuByCodeAndName", ReplyAction="http://tempuri.org/IService/GetSasiuByCodeAndNameResponse")]
        ProjectCarService.Sasiu GetSasiuByCodeAndName(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiuByCodeAndName", ReplyAction="http://tempuri.org/IService/GetSasiuByCodeAndNameResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Sasiu> GetSasiuByCodeAndNameAsync(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClient", ReplyAction="http://tempuri.org/IService/GetClientResponse")]
        ProjectCarService.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClient", ReplyAction="http://tempuri.org/IService/GetClientResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiu", ReplyAction="http://tempuri.org/IService/GetSasiuResponse")]
        ProjectCarService.Sasiu GetSasiu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiu", ReplyAction="http://tempuri.org/IService/GetSasiuResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Sasiu> GetSasiuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuto", ReplyAction="http://tempuri.org/IService/GetAutoResponse")]
        ProjectCarService.Auto GetAuto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuto", ReplyAction="http://tempuri.org/IService/GetAutoResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Auto> GetAutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComanda", ReplyAction="http://tempuri.org/IService/GetComandaResponse")]
        ProjectCarService.Comanda GetComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComanda", ReplyAction="http://tempuri.org/IService/GetComandaResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Comanda> GetComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDetaliuComanda", ReplyAction="http://tempuri.org/IService/GetDetaliuComandaResponse")]
        ProjectCarService.DetaliuComanda GetDetaliuComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDetaliuComanda", ReplyAction="http://tempuri.org/IService/GetDetaliuComandaResponse")]
        System.Threading.Tasks.Task<ProjectCarService.DetaliuComanda> GetDetaliuComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagine", ReplyAction="http://tempuri.org/IService/GetImagineResponse")]
        ProjectCarService.Imagine GetImagine(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagine", ReplyAction="http://tempuri.org/IService/GetImagineResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Imagine> GetImagineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterial", ReplyAction="http://tempuri.org/IService/GetMaterialResponse")]
        ProjectCarService.Material GetMaterial(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterial", ReplyAction="http://tempuri.org/IService/GetMaterialResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Material> GetMaterialAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMecanic", ReplyAction="http://tempuri.org/IService/GetMecanicResponse")]
        ProjectCarService.Mecanic GetMecanic(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMecanic", ReplyAction="http://tempuri.org/IService/GetMecanicResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Mecanic> GetMecanicAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperatie", ReplyAction="http://tempuri.org/IService/GetOperatieResponse")]
        ProjectCarService.Operatie GetOperatie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperatie", ReplyAction="http://tempuri.org/IService/GetOperatieResponse")]
        System.Threading.Tasks.Task<ProjectCarService.Operatie> GetOperatieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClientAutoSasiu", ReplyAction="http://tempuri.org/IService/DeleteClientAutoSasiuResponse")]
        void DeleteClientAutoSasiu(int idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClientAutoSasiu", ReplyAction="http://tempuri.org/IService/DeleteClientAutoSasiuResponse")]
        System.Threading.Tasks.Task DeleteClientAutoSasiuAsync(int idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClient", ReplyAction="http://tempuri.org/IService/DeleteClientResponse")]
        void DeleteClient(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClient", ReplyAction="http://tempuri.org/IService/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAuto", ReplyAction="http://tempuri.org/IService/DeleteAutoResponse")]
        void DeleteAuto(int autoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAuto", ReplyAction="http://tempuri.org/IService/DeleteAutoResponse")]
        System.Threading.Tasks.Task DeleteAutoAsync(int autoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteComanda", ReplyAction="http://tempuri.org/IService/DeleteComandaResponse")]
        void DeleteComanda(int comandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteComanda", ReplyAction="http://tempuri.org/IService/DeleteComandaResponse")]
        System.Threading.Tasks.Task DeleteComandaAsync(int comandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMaterial", ReplyAction="http://tempuri.org/IService/DeleteMaterialResponse")]
        void DeleteMaterial(int materialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMaterial", ReplyAction="http://tempuri.org/IService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task DeleteMaterialAsync(int materialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMecanic", ReplyAction="http://tempuri.org/IService/DeleteMecanicResponse")]
        void DeleteMecanic(int mecanicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMecanic", ReplyAction="http://tempuri.org/IService/DeleteMecanicResponse")]
        System.Threading.Tasks.Task DeleteMecanicAsync(int mecanicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperatie", ReplyAction="http://tempuri.org/IService/DeleteOperatieResponse")]
        void DeleteOperatie(int operatieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperatie", ReplyAction="http://tempuri.org/IService/DeleteOperatieResponse")]
        System.Threading.Tasks.Task DeleteOperatieAsync(int operatieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteSasiu", ReplyAction="http://tempuri.org/IService/DeleteSasiuResponse")]
        void DeleteSasiu(int sasiuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteSasiu", ReplyAction="http://tempuri.org/IService/DeleteSasiuResponse")]
        System.Threading.Tasks.Task DeleteSasiuAsync(int sasiuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/IService/DeleteDetaliuComandaResponse")]
        void DeleteDetaliuComanda(int detaliuComandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/IService/DeleteDetaliuComandaResponse")]
        System.Threading.Tasks.Task DeleteDetaliuComandaAsync(int detaliuComandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        void DeleteImage(int imagineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        System.Threading.Tasks.Task DeleteImageAsync(int imagineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClient", ReplyAction="http://tempuri.org/IService/UpdateClientResponse")]
        void UpdateClient(ProjectCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClient", ReplyAction="http://tempuri.org/IService/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(ProjectCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAuto", ReplyAction="http://tempuri.org/IService/UpdateAutoResponse")]
        void UpdateAuto(ProjectCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAuto", ReplyAction="http://tempuri.org/IService/UpdateAutoResponse")]
        System.Threading.Tasks.Task UpdateAutoAsync(ProjectCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateComanda", ReplyAction="http://tempuri.org/IService/UpdateComandaResponse")]
        void UpdateComanda(ProjectCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateComanda", ReplyAction="http://tempuri.org/IService/UpdateComandaResponse")]
        System.Threading.Tasks.Task UpdateComandaAsync(ProjectCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IService/UpdateDetaliuComandaResponse")]
        void UpdateDetaliuComanda(ProjectCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IService/UpdateDetaliuComandaResponse")]
        System.Threading.Tasks.Task UpdateDetaliuComandaAsync(ProjectCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateImaine", ReplyAction="http://tempuri.org/IService/UpdateImaineResponse")]
        void UpdateImaine(ProjectCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateImaine", ReplyAction="http://tempuri.org/IService/UpdateImaineResponse")]
        System.Threading.Tasks.Task UpdateImaineAsync(ProjectCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMaterial", ReplyAction="http://tempuri.org/IService/UpdateMaterialResponse")]
        void UpdateMaterial(ProjectCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMaterial", ReplyAction="http://tempuri.org/IService/UpdateMaterialResponse")]
        System.Threading.Tasks.Task UpdateMaterialAsync(ProjectCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMecanic", ReplyAction="http://tempuri.org/IService/UpdateMecanicResponse")]
        void UpdateMecanic(ProjectCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMecanic", ReplyAction="http://tempuri.org/IService/UpdateMecanicResponse")]
        System.Threading.Tasks.Task UpdateMecanicAsync(ProjectCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateOperatie", ReplyAction="http://tempuri.org/IService/UpdateOperatieResponse")]
        void UpdateOperatie(ProjectCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateOperatie", ReplyAction="http://tempuri.org/IService/UpdateOperatieResponse")]
        System.Threading.Tasks.Task UpdateOperatieAsync(ProjectCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSasiu", ReplyAction="http://tempuri.org/IService/UpdateSasiuResponse")]
        void UpdateSasiu(ProjectCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSasiu", ReplyAction="http://tempuri.org/IService/UpdateSasiuResponse")]
        System.Threading.Tasks.Task UpdateSasiuAsync(ProjectCarService.Sasiu sasiu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CarServiceUI.WCFCarService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CarServiceUI.WCFCarService.IService>, CarServiceUI.WCFCarService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddClient(ProjectCarService.Client client) {
            base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(ProjectCarService.Client client) {
            return base.Channel.AddClientAsync(client);
        }
        
        public void AddAuto(ProjectCarService.Auto auto) {
            base.Channel.AddAuto(auto);
        }
        
        public System.Threading.Tasks.Task AddAutoAsync(ProjectCarService.Auto auto) {
            return base.Channel.AddAutoAsync(auto);
        }
        
        public void AddComanda(ProjectCarService.Comanda comanda) {
            base.Channel.AddComanda(comanda);
        }
        
        public System.Threading.Tasks.Task AddComandaAsync(ProjectCarService.Comanda comanda) {
            return base.Channel.AddComandaAsync(comanda);
        }
        
        public void AddDetaliuComanda(ProjectCarService.DetaliuComanda detaliuComanda) {
            base.Channel.AddDetaliuComanda(detaliuComanda);
        }
        
        public System.Threading.Tasks.Task AddDetaliuComandaAsync(ProjectCarService.DetaliuComanda detaliuComanda) {
            return base.Channel.AddDetaliuComandaAsync(detaliuComanda);
        }
        
        public void AddImage(ProjectCarService.Imagine imagine) {
            base.Channel.AddImage(imagine);
        }
        
        public System.Threading.Tasks.Task AddImageAsync(ProjectCarService.Imagine imagine) {
            return base.Channel.AddImageAsync(imagine);
        }
        
        public void AddMaterial(ProjectCarService.Material material) {
            base.Channel.AddMaterial(material);
        }
        
        public System.Threading.Tasks.Task AddMaterialAsync(ProjectCarService.Material material) {
            return base.Channel.AddMaterialAsync(material);
        }
        
        public void AddMecanic(ProjectCarService.Mecanic mecanic) {
            base.Channel.AddMecanic(mecanic);
        }
        
        public System.Threading.Tasks.Task AddMecanicAsync(ProjectCarService.Mecanic mecanic) {
            return base.Channel.AddMecanicAsync(mecanic);
        }
        
        public void AddOperatie(ProjectCarService.Operatie operatie) {
            base.Channel.AddOperatie(operatie);
        }
        
        public System.Threading.Tasks.Task AddOperatieAsync(ProjectCarService.Operatie operatie) {
            return base.Channel.AddOperatieAsync(operatie);
        }
        
        public void AddSasiu(ProjectCarService.Sasiu sasiu) {
            base.Channel.AddSasiu(sasiu);
        }
        
        public System.Threading.Tasks.Task AddSasiuAsync(ProjectCarService.Sasiu sasiu) {
            return base.Channel.AddSasiuAsync(sasiu);
        }
        
        public ProjectCarService.Auto[] GetAllAuto() {
            return base.Channel.GetAllAuto();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Auto[]> GetAllAutoAsync() {
            return base.Channel.GetAllAutoAsync();
        }
        
        public ProjectCarService.Auto[] GetAutoByClientId(int clientId) {
            return base.Channel.GetAutoByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Auto[]> GetAutoByClientIdAsync(int clientId) {
            return base.Channel.GetAutoByClientIdAsync(clientId);
        }
        
        public ProjectCarService.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public ProjectCarService.Comanda[] GetAllComands() {
            return base.Channel.GetAllComands();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Comanda[]> GetAllComandsAsync() {
            return base.Channel.GetAllComandsAsync();
        }
        
        public ProjectCarService.Material[] GetAllMaterials() {
            return base.Channel.GetAllMaterials();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Material[]> GetAllMaterialsAsync() {
            return base.Channel.GetAllMaterialsAsync();
        }
        
        public ProjectCarService.Mecanic[] GetAllMecanics() {
            return base.Channel.GetAllMecanics();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Mecanic[]> GetAllMecanicsAsync() {
            return base.Channel.GetAllMecanicsAsync();
        }
        
        public ProjectCarService.DetaliuComanda[] GetAllDetailsCommands() {
            return base.Channel.GetAllDetailsCommands();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.DetaliuComanda[]> GetAllDetailsCommandsAsync() {
            return base.Channel.GetAllDetailsCommandsAsync();
        }
        
        public ProjectCarService.Imagine[] GetAllImagies() {
            return base.Channel.GetAllImagies();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Imagine[]> GetAllImagiesAsync() {
            return base.Channel.GetAllImagiesAsync();
        }
        
        public ProjectCarService.Operatie[] GetOperations() {
            return base.Channel.GetOperations();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Operatie[]> GetOperationsAsync() {
            return base.Channel.GetOperationsAsync();
        }
        
        public ProjectCarService.Sasiu[] GetAllChassis() {
            return base.Channel.GetAllChassis();
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Sasiu[]> GetAllChassisAsync() {
            return base.Channel.GetAllChassisAsync();
        }
        
        public ProjectCarService.Sasiu GetSasiuByCodeAndName(string code, string name) {
            return base.Channel.GetSasiuByCodeAndName(code, name);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Sasiu> GetSasiuByCodeAndNameAsync(string code, string name) {
            return base.Channel.GetSasiuByCodeAndNameAsync(code, name);
        }
        
        public ProjectCarService.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public ProjectCarService.Sasiu GetSasiu(int id) {
            return base.Channel.GetSasiu(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Sasiu> GetSasiuAsync(int id) {
            return base.Channel.GetSasiuAsync(id);
        }
        
        public ProjectCarService.Auto GetAuto(int id) {
            return base.Channel.GetAuto(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Auto> GetAutoAsync(int id) {
            return base.Channel.GetAutoAsync(id);
        }
        
        public ProjectCarService.Comanda GetComanda(int id) {
            return base.Channel.GetComanda(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Comanda> GetComandaAsync(int id) {
            return base.Channel.GetComandaAsync(id);
        }
        
        public ProjectCarService.DetaliuComanda GetDetaliuComanda(int id) {
            return base.Channel.GetDetaliuComanda(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.DetaliuComanda> GetDetaliuComandaAsync(int id) {
            return base.Channel.GetDetaliuComandaAsync(id);
        }
        
        public ProjectCarService.Imagine GetImagine(int id) {
            return base.Channel.GetImagine(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Imagine> GetImagineAsync(int id) {
            return base.Channel.GetImagineAsync(id);
        }
        
        public ProjectCarService.Material GetMaterial(int id) {
            return base.Channel.GetMaterial(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Material> GetMaterialAsync(int id) {
            return base.Channel.GetMaterialAsync(id);
        }
        
        public ProjectCarService.Mecanic GetMecanic(int id) {
            return base.Channel.GetMecanic(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Mecanic> GetMecanicAsync(int id) {
            return base.Channel.GetMecanicAsync(id);
        }
        
        public ProjectCarService.Operatie GetOperatie(int id) {
            return base.Channel.GetOperatie(id);
        }
        
        public System.Threading.Tasks.Task<ProjectCarService.Operatie> GetOperatieAsync(int id) {
            return base.Channel.GetOperatieAsync(id);
        }
        
        public void DeleteClientAutoSasiu(int idClient) {
            base.Channel.DeleteClientAutoSasiu(idClient);
        }
        
        public System.Threading.Tasks.Task DeleteClientAutoSasiuAsync(int idClient) {
            return base.Channel.DeleteClientAutoSasiuAsync(idClient);
        }
        
        public void DeleteClient(int clientId) {
            base.Channel.DeleteClient(clientId);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(int clientId) {
            return base.Channel.DeleteClientAsync(clientId);
        }
        
        public void DeleteAuto(int autoId) {
            base.Channel.DeleteAuto(autoId);
        }
        
        public System.Threading.Tasks.Task DeleteAutoAsync(int autoId) {
            return base.Channel.DeleteAutoAsync(autoId);
        }
        
        public void DeleteComanda(int comandaId) {
            base.Channel.DeleteComanda(comandaId);
        }
        
        public System.Threading.Tasks.Task DeleteComandaAsync(int comandaId) {
            return base.Channel.DeleteComandaAsync(comandaId);
        }
        
        public void DeleteMaterial(int materialId) {
            base.Channel.DeleteMaterial(materialId);
        }
        
        public System.Threading.Tasks.Task DeleteMaterialAsync(int materialId) {
            return base.Channel.DeleteMaterialAsync(materialId);
        }
        
        public void DeleteMecanic(int mecanicId) {
            base.Channel.DeleteMecanic(mecanicId);
        }
        
        public System.Threading.Tasks.Task DeleteMecanicAsync(int mecanicId) {
            return base.Channel.DeleteMecanicAsync(mecanicId);
        }
        
        public void DeleteOperatie(int operatieId) {
            base.Channel.DeleteOperatie(operatieId);
        }
        
        public System.Threading.Tasks.Task DeleteOperatieAsync(int operatieId) {
            return base.Channel.DeleteOperatieAsync(operatieId);
        }
        
        public void DeleteSasiu(int sasiuId) {
            base.Channel.DeleteSasiu(sasiuId);
        }
        
        public System.Threading.Tasks.Task DeleteSasiuAsync(int sasiuId) {
            return base.Channel.DeleteSasiuAsync(sasiuId);
        }
        
        public void DeleteDetaliuComanda(int detaliuComandaId) {
            base.Channel.DeleteDetaliuComanda(detaliuComandaId);
        }
        
        public System.Threading.Tasks.Task DeleteDetaliuComandaAsync(int detaliuComandaId) {
            return base.Channel.DeleteDetaliuComandaAsync(detaliuComandaId);
        }
        
        public void DeleteImage(int imagineId) {
            base.Channel.DeleteImage(imagineId);
        }
        
        public System.Threading.Tasks.Task DeleteImageAsync(int imagineId) {
            return base.Channel.DeleteImageAsync(imagineId);
        }
        
        public void UpdateClient(ProjectCarService.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(ProjectCarService.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public void UpdateAuto(ProjectCarService.Auto auto) {
            base.Channel.UpdateAuto(auto);
        }
        
        public System.Threading.Tasks.Task UpdateAutoAsync(ProjectCarService.Auto auto) {
            return base.Channel.UpdateAutoAsync(auto);
        }
        
        public void UpdateComanda(ProjectCarService.Comanda comanda) {
            base.Channel.UpdateComanda(comanda);
        }
        
        public System.Threading.Tasks.Task UpdateComandaAsync(ProjectCarService.Comanda comanda) {
            return base.Channel.UpdateComandaAsync(comanda);
        }
        
        public void UpdateDetaliuComanda(ProjectCarService.DetaliuComanda detaliuComanda) {
            base.Channel.UpdateDetaliuComanda(detaliuComanda);
        }
        
        public System.Threading.Tasks.Task UpdateDetaliuComandaAsync(ProjectCarService.DetaliuComanda detaliuComanda) {
            return base.Channel.UpdateDetaliuComandaAsync(detaliuComanda);
        }
        
        public void UpdateImaine(ProjectCarService.Imagine imagine) {
            base.Channel.UpdateImaine(imagine);
        }
        
        public System.Threading.Tasks.Task UpdateImaineAsync(ProjectCarService.Imagine imagine) {
            return base.Channel.UpdateImaineAsync(imagine);
        }
        
        public void UpdateMaterial(ProjectCarService.Material material) {
            base.Channel.UpdateMaterial(material);
        }
        
        public System.Threading.Tasks.Task UpdateMaterialAsync(ProjectCarService.Material material) {
            return base.Channel.UpdateMaterialAsync(material);
        }
        
        public void UpdateMecanic(ProjectCarService.Mecanic mecanic) {
            base.Channel.UpdateMecanic(mecanic);
        }
        
        public System.Threading.Tasks.Task UpdateMecanicAsync(ProjectCarService.Mecanic mecanic) {
            return base.Channel.UpdateMecanicAsync(mecanic);
        }
        
        public void UpdateOperatie(ProjectCarService.Operatie operatie) {
            base.Channel.UpdateOperatie(operatie);
        }
        
        public System.Threading.Tasks.Task UpdateOperatieAsync(ProjectCarService.Operatie operatie) {
            return base.Channel.UpdateOperatieAsync(operatie);
        }
        
        public void UpdateSasiu(ProjectCarService.Sasiu sasiu) {
            base.Channel.UpdateSasiu(sasiu);
        }
        
        public System.Threading.Tasks.Task UpdateSasiuAsync(ProjectCarService.Sasiu sasiu) {
            return base.Channel.UpdateSasiuAsync(sasiu);
        }
    }
}
