//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCarService.WCFHostCarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Auto[] AutoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Comanda[] ComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Auto[] Autoes {
            get {
                return this.AutoesField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoesField, value) != true)) {
                    this.AutoesField = value;
                    this.RaisePropertyChanged("Autoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Comanda[] Comandas {
            get {
                return this.ComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandasField, value) != true)) {
                    this.ComandasField = value;
                    this.RaisePropertyChanged("Comandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet {
            get {
                return this.JudetField;
            }
            set {
                if ((object.ReferenceEquals(this.JudetField, value) != true)) {
                    this.JudetField = value;
                    this.RaisePropertyChanged("Judet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate {
            get {
                return this.LocalitateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitateField, value) != true)) {
                    this.LocalitateField = value;
                    this.RaisePropertyChanged("Localitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumarAutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Sasiu SasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuSasiuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieSasiuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientClientId {
            get {
                return this.ClientClientIdField;
            }
            set {
                if ((this.ClientClientIdField.Equals(value) != true)) {
                    this.ClientClientIdField = value;
                    this.RaisePropertyChanged("ClientClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto {
            get {
                return this.NumarAutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumarAutoField, value) != true)) {
                    this.NumarAutoField = value;
                    this.RaisePropertyChanged("NumarAuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Sasiu Sasiu {
            get {
                return this.SasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SasiuField, value) != true)) {
                    this.SasiuField = value;
                    this.RaisePropertyChanged("Sasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuSasiuId {
            get {
                return this.SasiuSasiuIdField;
            }
            set {
                if ((this.SasiuSasiuIdField.Equals(value) != true)) {
                    this.SasiuSasiuIdField = value;
                    this.RaisePropertyChanged("SasiuSasiuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu {
            get {
                return this.SerieSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieSasiuField, value) != true)) {
                    this.SerieSasiuField = value;
                    this.RaisePropertyChanged("SerieSasiu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFinalizareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataProgramareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KmBordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StareComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValoarePiseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientClientId {
            get {
                return this.ClientClientIdField;
            }
            set {
                if ((this.ClientClientIdField.Equals(value) != true)) {
                    this.ClientClientIdField = value;
                    this.RaisePropertyChanged("ClientClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId {
            get {
                return this.ComandaIdField;
            }
            set {
                if ((this.ComandaIdField.Equals(value) != true)) {
                    this.ComandaIdField = value;
                    this.RaisePropertyChanged("ComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizare {
            get {
                return this.DataFinalizareField;
            }
            set {
                if ((this.DataFinalizareField.Equals(value) != true)) {
                    this.DataFinalizareField = value;
                    this.RaisePropertyChanged("DataFinalizare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare {
            get {
                return this.DataProgramareField;
            }
            set {
                if ((this.DataProgramareField.Equals(value) != true)) {
                    this.DataProgramareField = value;
                    this.RaisePropertyChanged("DataProgramare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem {
            get {
                return this.DataSystemField;
            }
            set {
                if ((this.DataSystemField.Equals(value) != true)) {
                    this.DataSystemField = value;
                    this.RaisePropertyChanged("DataSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KmBord {
            get {
                return this.KmBordField;
            }
            set {
                if ((this.KmBordField.Equals(value) != true)) {
                    this.KmBordField = value;
                    this.RaisePropertyChanged("KmBord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StareComanda {
            get {
                return this.StareComandaField;
            }
            set {
                if ((this.StareComandaField.Equals(value) != true)) {
                    this.StareComandaField = value;
                    this.RaisePropertyChanged("StareComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValoarePise {
            get {
                return this.ValoarePiseField;
            }
            set {
                if ((this.ValoarePiseField.Equals(value) != true)) {
                    this.ValoarePiseField = value;
                    this.RaisePropertyChanged("ValoarePise");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Auto[] AutoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodSasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Auto[] Autoes {
            get {
                return this.AutoesField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoesField, value) != true)) {
                    this.AutoesField = value;
                    this.RaisePropertyChanged("Autoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu {
            get {
                return this.CodSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSasiuField, value) != true)) {
                    this.CodSasiuField = value;
                    this.RaisePropertyChanged("CodSasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId {
            get {
                return this.SasiuIdField;
            }
            set {
                if ((this.SasiuIdField.Equals(value) != true)) {
                    this.SasiuIdField = value;
                    this.RaisePropertyChanged("SasiuId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Comanda ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetaliuComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Imagine[] ImaginesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Material[] MaterialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Mecanic[] MecanicsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.Operatie[] OperatiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Comanda Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliuComandaId {
            get {
                return this.DetaliuComandaIdField;
            }
            set {
                if ((this.DetaliuComandaIdField.Equals(value) != true)) {
                    this.DetaliuComandaIdField = value;
                    this.RaisePropertyChanged("DetaliuComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Imagine[] Imagines {
            get {
                return this.ImaginesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImaginesField, value) != true)) {
                    this.ImaginesField = value;
                    this.RaisePropertyChanged("Imagines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Material[] Materials {
            get {
                return this.MaterialsField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialsField, value) != true)) {
                    this.MaterialsField = value;
                    this.RaisePropertyChanged("Materials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Mecanic[] Mecanics {
            get {
                return this.MecanicsField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicsField, value) != true)) {
                    this.MecanicsField = value;
                    this.RaisePropertyChanged("Mecanics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.Operatie[] Operaties {
            get {
                return this.OperatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatiesField, value) != true)) {
                    this.OperatiesField = value;
                    this.RaisePropertyChanged("Operaties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImagineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitluField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagineId {
            get {
                return this.ImagineIdField;
            }
            set {
                if ((this.ImagineIdField.Equals(value) != true)) {
                    this.ImagineIdField = value;
                    this.RaisePropertyChanged("ImagineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu {
            get {
                return this.TitluField;
            }
            set {
                if ((object.ReferenceEquals(this.TitluField, value) != true)) {
                    this.TitluField = value;
                    this.RaisePropertyChanged("Titlu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset DataAprovizionareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate {
            get {
                return this.CantitateField;
            }
            set {
                if ((this.CantitateField.Equals(value) != true)) {
                    this.CantitateField = value;
                    this.RaisePropertyChanged("Cantitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset DataAprovizionare {
            get {
                return this.DataAprovizionareField;
            }
            set {
                if ((this.DataAprovizionareField.Equals(value) != true)) {
                    this.DataAprovizionareField = value;
                    this.RaisePropertyChanged("DataAprovizionare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((this.MaterialIdField.Equals(value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret {
            get {
                return this.PretField;
            }
            set {
                if ((this.PretField.Equals(value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.DetaliuComanda[] DetaliuComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MecanicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.DetaliuComanda[] DetaliuComandas {
            get {
                return this.DetaliuComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandasField, value) != true)) {
                    this.DetaliuComandasField = value;
                    this.RaisePropertyChanged("DetaliuComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId {
            get {
                return this.MecanicIdField;
            }
            set {
                if ((this.MecanicIdField.Equals(value) != true)) {
                    this.MecanicIdField = value;
                    this.RaisePropertyChanged("MecanicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/ProjectCarService")]
    [System.SerializableAttribute()]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TimpExecutieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFCarService.WCFHostCarService.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId {
            get {
                return this.OperatieIdField;
            }
            set {
                if ((this.OperatieIdField.Equals(value) != true)) {
                    this.OperatieIdField = value;
                    this.RaisePropertyChanged("OperatieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie {
            get {
                return this.TimpExecutieField;
            }
            set {
                if ((this.TimpExecutieField.Equals(value) != true)) {
                    this.TimpExecutieField = value;
                    this.RaisePropertyChanged("TimpExecutie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFHostCarService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddClient", ReplyAction="http://tempuri.org/IService/AddClientResponse")]
        void AddClient(WPFCarService.WCFHostCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddClient", ReplyAction="http://tempuri.org/IService/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(WPFCarService.WCFHostCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddAuto", ReplyAction="http://tempuri.org/IService/AddAutoResponse")]
        void AddAuto(WPFCarService.WCFHostCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddAuto", ReplyAction="http://tempuri.org/IService/AddAutoResponse")]
        System.Threading.Tasks.Task AddAutoAsync(WPFCarService.WCFHostCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddComanda", ReplyAction="http://tempuri.org/IService/AddComandaResponse")]
        void AddComanda(WPFCarService.WCFHostCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddComanda", ReplyAction="http://tempuri.org/IService/AddComandaResponse")]
        System.Threading.Tasks.Task AddComandaAsync(WPFCarService.WCFHostCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDetaliuComanda", ReplyAction="http://tempuri.org/IService/AddDetaliuComandaResponse")]
        void AddDetaliuComanda(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDetaliuComanda", ReplyAction="http://tempuri.org/IService/AddDetaliuComandaResponse")]
        System.Threading.Tasks.Task AddDetaliuComandaAsync(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddImage", ReplyAction="http://tempuri.org/IService/AddImageResponse")]
        void AddImage(WPFCarService.WCFHostCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddImage", ReplyAction="http://tempuri.org/IService/AddImageResponse")]
        System.Threading.Tasks.Task AddImageAsync(WPFCarService.WCFHostCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMaterial", ReplyAction="http://tempuri.org/IService/AddMaterialResponse")]
        void AddMaterial(WPFCarService.WCFHostCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMaterial", ReplyAction="http://tempuri.org/IService/AddMaterialResponse")]
        System.Threading.Tasks.Task AddMaterialAsync(WPFCarService.WCFHostCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMecanic", ReplyAction="http://tempuri.org/IService/AddMecanicResponse")]
        void AddMecanic(WPFCarService.WCFHostCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMecanic", ReplyAction="http://tempuri.org/IService/AddMecanicResponse")]
        System.Threading.Tasks.Task AddMecanicAsync(WPFCarService.WCFHostCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddOperatie", ReplyAction="http://tempuri.org/IService/AddOperatieResponse")]
        void AddOperatie(WPFCarService.WCFHostCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddOperatie", ReplyAction="http://tempuri.org/IService/AddOperatieResponse")]
        System.Threading.Tasks.Task AddOperatieAsync(WPFCarService.WCFHostCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSasiu", ReplyAction="http://tempuri.org/IService/AddSasiuResponse")]
        void AddSasiu(WPFCarService.WCFHostCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSasiu", ReplyAction="http://tempuri.org/IService/AddSasiuResponse")]
        System.Threading.Tasks.Task AddSasiuAsync(WPFCarService.WCFHostCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuto", ReplyAction="http://tempuri.org/IService/GetAllAutoResponse")]
        WPFCarService.WCFHostCarService.Auto[] GetAllAuto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuto", ReplyAction="http://tempuri.org/IService/GetAllAutoResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto[]> GetAllAutoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAutoByClientId", ReplyAction="http://tempuri.org/IService/GetAutoByClientIdResponse")]
        WPFCarService.WCFHostCarService.Auto[] GetAutoByClientId(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAutoByClientId", ReplyAction="http://tempuri.org/IService/GetAutoByClientIdResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto[]> GetAutoByClientIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClients", ReplyAction="http://tempuri.org/IService/GetAllClientsResponse")]
        WPFCarService.WCFHostCarService.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClients", ReplyAction="http://tempuri.org/IService/GetAllClientsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllComands", ReplyAction="http://tempuri.org/IService/GetAllComandsResponse")]
        WPFCarService.WCFHostCarService.Comanda[] GetAllComands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllComands", ReplyAction="http://tempuri.org/IService/GetAllComandsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Comanda[]> GetAllComandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMaterials", ReplyAction="http://tempuri.org/IService/GetAllMaterialsResponse")]
        WPFCarService.WCFHostCarService.Material[] GetAllMaterials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMaterials", ReplyAction="http://tempuri.org/IService/GetAllMaterialsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Material[]> GetAllMaterialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMecanics", ReplyAction="http://tempuri.org/IService/GetAllMecanicsResponse")]
        WPFCarService.WCFHostCarService.Mecanic[] GetAllMecanics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMecanics", ReplyAction="http://tempuri.org/IService/GetAllMecanicsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Mecanic[]> GetAllMecanicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDetailsCommands", ReplyAction="http://tempuri.org/IService/GetAllDetailsCommandsResponse")]
        WPFCarService.WCFHostCarService.DetaliuComanda[] GetAllDetailsCommands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDetailsCommands", ReplyAction="http://tempuri.org/IService/GetAllDetailsCommandsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.DetaliuComanda[]> GetAllDetailsCommandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllImagies", ReplyAction="http://tempuri.org/IService/GetAllImagiesResponse")]
        WPFCarService.WCFHostCarService.Imagine[] GetAllImagies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllImagies", ReplyAction="http://tempuri.org/IService/GetAllImagiesResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Imagine[]> GetAllImagiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperations", ReplyAction="http://tempuri.org/IService/GetOperationsResponse")]
        WPFCarService.WCFHostCarService.Operatie[] GetOperations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperations", ReplyAction="http://tempuri.org/IService/GetOperationsResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Operatie[]> GetOperationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllChassis", ReplyAction="http://tempuri.org/IService/GetAllChassisResponse")]
        WPFCarService.WCFHostCarService.Sasiu[] GetAllChassis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllChassis", ReplyAction="http://tempuri.org/IService/GetAllChassisResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu[]> GetAllChassisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiuByCodeAndName", ReplyAction="http://tempuri.org/IService/GetSasiuByCodeAndNameResponse")]
        WPFCarService.WCFHostCarService.Sasiu GetSasiuByCodeAndName(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiuByCodeAndName", ReplyAction="http://tempuri.org/IService/GetSasiuByCodeAndNameResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu> GetSasiuByCodeAndNameAsync(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClient", ReplyAction="http://tempuri.org/IService/GetClientResponse")]
        WPFCarService.WCFHostCarService.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClient", ReplyAction="http://tempuri.org/IService/GetClientResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiu", ReplyAction="http://tempuri.org/IService/GetSasiuResponse")]
        WPFCarService.WCFHostCarService.Sasiu GetSasiu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSasiu", ReplyAction="http://tempuri.org/IService/GetSasiuResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu> GetSasiuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuto", ReplyAction="http://tempuri.org/IService/GetAutoResponse")]
        WPFCarService.WCFHostCarService.Auto GetAuto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuto", ReplyAction="http://tempuri.org/IService/GetAutoResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto> GetAutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComanda", ReplyAction="http://tempuri.org/IService/GetComandaResponse")]
        WPFCarService.WCFHostCarService.Comanda GetComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComanda", ReplyAction="http://tempuri.org/IService/GetComandaResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Comanda> GetComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDetaliuComanda", ReplyAction="http://tempuri.org/IService/GetDetaliuComandaResponse")]
        WPFCarService.WCFHostCarService.DetaliuComanda GetDetaliuComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDetaliuComanda", ReplyAction="http://tempuri.org/IService/GetDetaliuComandaResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.DetaliuComanda> GetDetaliuComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagine", ReplyAction="http://tempuri.org/IService/GetImagineResponse")]
        WPFCarService.WCFHostCarService.Imagine GetImagine(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagine", ReplyAction="http://tempuri.org/IService/GetImagineResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Imagine> GetImagineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterial", ReplyAction="http://tempuri.org/IService/GetMaterialResponse")]
        WPFCarService.WCFHostCarService.Material GetMaterial(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterial", ReplyAction="http://tempuri.org/IService/GetMaterialResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Material> GetMaterialAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMecanic", ReplyAction="http://tempuri.org/IService/GetMecanicResponse")]
        WPFCarService.WCFHostCarService.Mecanic GetMecanic(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMecanic", ReplyAction="http://tempuri.org/IService/GetMecanicResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Mecanic> GetMecanicAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperatie", ReplyAction="http://tempuri.org/IService/GetOperatieResponse")]
        WPFCarService.WCFHostCarService.Operatie GetOperatie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperatie", ReplyAction="http://tempuri.org/IService/GetOperatieResponse")]
        System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Operatie> GetOperatieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClientAutoSasiu", ReplyAction="http://tempuri.org/IService/DeleteClientAutoSasiuResponse")]
        void DeleteClientAutoSasiu(int idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClientAutoSasiu", ReplyAction="http://tempuri.org/IService/DeleteClientAutoSasiuResponse")]
        System.Threading.Tasks.Task DeleteClientAutoSasiuAsync(int idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClient", ReplyAction="http://tempuri.org/IService/DeleteClientResponse")]
        void DeleteClient(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClient", ReplyAction="http://tempuri.org/IService/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAuto", ReplyAction="http://tempuri.org/IService/DeleteAutoResponse")]
        void DeleteAuto(int autoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAuto", ReplyAction="http://tempuri.org/IService/DeleteAutoResponse")]
        System.Threading.Tasks.Task DeleteAutoAsync(int autoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteComanda", ReplyAction="http://tempuri.org/IService/DeleteComandaResponse")]
        void DeleteComanda(int comandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteComanda", ReplyAction="http://tempuri.org/IService/DeleteComandaResponse")]
        System.Threading.Tasks.Task DeleteComandaAsync(int comandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMaterial", ReplyAction="http://tempuri.org/IService/DeleteMaterialResponse")]
        void DeleteMaterial(int materialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMaterial", ReplyAction="http://tempuri.org/IService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task DeleteMaterialAsync(int materialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMecanic", ReplyAction="http://tempuri.org/IService/DeleteMecanicResponse")]
        void DeleteMecanic(int mecanicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMecanic", ReplyAction="http://tempuri.org/IService/DeleteMecanicResponse")]
        System.Threading.Tasks.Task DeleteMecanicAsync(int mecanicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperatie", ReplyAction="http://tempuri.org/IService/DeleteOperatieResponse")]
        void DeleteOperatie(int operatieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperatie", ReplyAction="http://tempuri.org/IService/DeleteOperatieResponse")]
        System.Threading.Tasks.Task DeleteOperatieAsync(int operatieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteSasiu", ReplyAction="http://tempuri.org/IService/DeleteSasiuResponse")]
        void DeleteSasiu(int sasiuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteSasiu", ReplyAction="http://tempuri.org/IService/DeleteSasiuResponse")]
        System.Threading.Tasks.Task DeleteSasiuAsync(int sasiuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/IService/DeleteDetaliuComandaResponse")]
        void DeleteDetaliuComanda(int detaliuComandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/IService/DeleteDetaliuComandaResponse")]
        System.Threading.Tasks.Task DeleteDetaliuComandaAsync(int detaliuComandaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        void DeleteImage(int imagineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        System.Threading.Tasks.Task DeleteImageAsync(int imagineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClient", ReplyAction="http://tempuri.org/IService/UpdateClientResponse")]
        void UpdateClient(WPFCarService.WCFHostCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClient", ReplyAction="http://tempuri.org/IService/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(WPFCarService.WCFHostCarService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAuto", ReplyAction="http://tempuri.org/IService/UpdateAutoResponse")]
        void UpdateAuto(WPFCarService.WCFHostCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAuto", ReplyAction="http://tempuri.org/IService/UpdateAutoResponse")]
        System.Threading.Tasks.Task UpdateAutoAsync(WPFCarService.WCFHostCarService.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateComanda", ReplyAction="http://tempuri.org/IService/UpdateComandaResponse")]
        void UpdateComanda(WPFCarService.WCFHostCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateComanda", ReplyAction="http://tempuri.org/IService/UpdateComandaResponse")]
        System.Threading.Tasks.Task UpdateComandaAsync(WPFCarService.WCFHostCarService.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IService/UpdateDetaliuComandaResponse")]
        void UpdateDetaliuComanda(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IService/UpdateDetaliuComandaResponse")]
        System.Threading.Tasks.Task UpdateDetaliuComandaAsync(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateImaine", ReplyAction="http://tempuri.org/IService/UpdateImaineResponse")]
        void UpdateImaine(WPFCarService.WCFHostCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateImaine", ReplyAction="http://tempuri.org/IService/UpdateImaineResponse")]
        System.Threading.Tasks.Task UpdateImaineAsync(WPFCarService.WCFHostCarService.Imagine imagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMaterial", ReplyAction="http://tempuri.org/IService/UpdateMaterialResponse")]
        void UpdateMaterial(WPFCarService.WCFHostCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMaterial", ReplyAction="http://tempuri.org/IService/UpdateMaterialResponse")]
        System.Threading.Tasks.Task UpdateMaterialAsync(WPFCarService.WCFHostCarService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMecanic", ReplyAction="http://tempuri.org/IService/UpdateMecanicResponse")]
        void UpdateMecanic(WPFCarService.WCFHostCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMecanic", ReplyAction="http://tempuri.org/IService/UpdateMecanicResponse")]
        System.Threading.Tasks.Task UpdateMecanicAsync(WPFCarService.WCFHostCarService.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateOperatie", ReplyAction="http://tempuri.org/IService/UpdateOperatieResponse")]
        void UpdateOperatie(WPFCarService.WCFHostCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateOperatie", ReplyAction="http://tempuri.org/IService/UpdateOperatieResponse")]
        System.Threading.Tasks.Task UpdateOperatieAsync(WPFCarService.WCFHostCarService.Operatie operatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSasiu", ReplyAction="http://tempuri.org/IService/UpdateSasiuResponse")]
        void UpdateSasiu(WPFCarService.WCFHostCarService.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSasiu", ReplyAction="http://tempuri.org/IService/UpdateSasiuResponse")]
        System.Threading.Tasks.Task UpdateSasiuAsync(WPFCarService.WCFHostCarService.Sasiu sasiu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WPFCarService.WCFHostCarService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WPFCarService.WCFHostCarService.IService>, WPFCarService.WCFHostCarService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddClient(WPFCarService.WCFHostCarService.Client client) {
            base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(WPFCarService.WCFHostCarService.Client client) {
            return base.Channel.AddClientAsync(client);
        }
        
        public void AddAuto(WPFCarService.WCFHostCarService.Auto auto) {
            base.Channel.AddAuto(auto);
        }
        
        public System.Threading.Tasks.Task AddAutoAsync(WPFCarService.WCFHostCarService.Auto auto) {
            return base.Channel.AddAutoAsync(auto);
        }
        
        public void AddComanda(WPFCarService.WCFHostCarService.Comanda comanda) {
            base.Channel.AddComanda(comanda);
        }
        
        public System.Threading.Tasks.Task AddComandaAsync(WPFCarService.WCFHostCarService.Comanda comanda) {
            return base.Channel.AddComandaAsync(comanda);
        }
        
        public void AddDetaliuComanda(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda) {
            base.Channel.AddDetaliuComanda(detaliuComanda);
        }
        
        public System.Threading.Tasks.Task AddDetaliuComandaAsync(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda) {
            return base.Channel.AddDetaliuComandaAsync(detaliuComanda);
        }
        
        public void AddImage(WPFCarService.WCFHostCarService.Imagine imagine) {
            base.Channel.AddImage(imagine);
        }
        
        public System.Threading.Tasks.Task AddImageAsync(WPFCarService.WCFHostCarService.Imagine imagine) {
            return base.Channel.AddImageAsync(imagine);
        }
        
        public void AddMaterial(WPFCarService.WCFHostCarService.Material material) {
            base.Channel.AddMaterial(material);
        }
        
        public System.Threading.Tasks.Task AddMaterialAsync(WPFCarService.WCFHostCarService.Material material) {
            return base.Channel.AddMaterialAsync(material);
        }
        
        public void AddMecanic(WPFCarService.WCFHostCarService.Mecanic mecanic) {
            base.Channel.AddMecanic(mecanic);
        }
        
        public System.Threading.Tasks.Task AddMecanicAsync(WPFCarService.WCFHostCarService.Mecanic mecanic) {
            return base.Channel.AddMecanicAsync(mecanic);
        }
        
        public void AddOperatie(WPFCarService.WCFHostCarService.Operatie operatie) {
            base.Channel.AddOperatie(operatie);
        }
        
        public System.Threading.Tasks.Task AddOperatieAsync(WPFCarService.WCFHostCarService.Operatie operatie) {
            return base.Channel.AddOperatieAsync(operatie);
        }
        
        public void AddSasiu(WPFCarService.WCFHostCarService.Sasiu sasiu) {
            base.Channel.AddSasiu(sasiu);
        }
        
        public System.Threading.Tasks.Task AddSasiuAsync(WPFCarService.WCFHostCarService.Sasiu sasiu) {
            return base.Channel.AddSasiuAsync(sasiu);
        }
        
        public WPFCarService.WCFHostCarService.Auto[] GetAllAuto() {
            return base.Channel.GetAllAuto();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto[]> GetAllAutoAsync() {
            return base.Channel.GetAllAutoAsync();
        }
        
        public WPFCarService.WCFHostCarService.Auto[] GetAutoByClientId(int clientId) {
            return base.Channel.GetAutoByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto[]> GetAutoByClientIdAsync(int clientId) {
            return base.Channel.GetAutoByClientIdAsync(clientId);
        }
        
        public WPFCarService.WCFHostCarService.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public WPFCarService.WCFHostCarService.Comanda[] GetAllComands() {
            return base.Channel.GetAllComands();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Comanda[]> GetAllComandsAsync() {
            return base.Channel.GetAllComandsAsync();
        }
        
        public WPFCarService.WCFHostCarService.Material[] GetAllMaterials() {
            return base.Channel.GetAllMaterials();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Material[]> GetAllMaterialsAsync() {
            return base.Channel.GetAllMaterialsAsync();
        }
        
        public WPFCarService.WCFHostCarService.Mecanic[] GetAllMecanics() {
            return base.Channel.GetAllMecanics();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Mecanic[]> GetAllMecanicsAsync() {
            return base.Channel.GetAllMecanicsAsync();
        }
        
        public WPFCarService.WCFHostCarService.DetaliuComanda[] GetAllDetailsCommands() {
            return base.Channel.GetAllDetailsCommands();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.DetaliuComanda[]> GetAllDetailsCommandsAsync() {
            return base.Channel.GetAllDetailsCommandsAsync();
        }
        
        public WPFCarService.WCFHostCarService.Imagine[] GetAllImagies() {
            return base.Channel.GetAllImagies();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Imagine[]> GetAllImagiesAsync() {
            return base.Channel.GetAllImagiesAsync();
        }
        
        public WPFCarService.WCFHostCarService.Operatie[] GetOperations() {
            return base.Channel.GetOperations();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Operatie[]> GetOperationsAsync() {
            return base.Channel.GetOperationsAsync();
        }
        
        public WPFCarService.WCFHostCarService.Sasiu[] GetAllChassis() {
            return base.Channel.GetAllChassis();
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu[]> GetAllChassisAsync() {
            return base.Channel.GetAllChassisAsync();
        }
        
        public WPFCarService.WCFHostCarService.Sasiu GetSasiuByCodeAndName(string code, string name) {
            return base.Channel.GetSasiuByCodeAndName(code, name);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu> GetSasiuByCodeAndNameAsync(string code, string name) {
            return base.Channel.GetSasiuByCodeAndNameAsync(code, name);
        }
        
        public WPFCarService.WCFHostCarService.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Sasiu GetSasiu(int id) {
            return base.Channel.GetSasiu(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Sasiu> GetSasiuAsync(int id) {
            return base.Channel.GetSasiuAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Auto GetAuto(int id) {
            return base.Channel.GetAuto(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Auto> GetAutoAsync(int id) {
            return base.Channel.GetAutoAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Comanda GetComanda(int id) {
            return base.Channel.GetComanda(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Comanda> GetComandaAsync(int id) {
            return base.Channel.GetComandaAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.DetaliuComanda GetDetaliuComanda(int id) {
            return base.Channel.GetDetaliuComanda(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.DetaliuComanda> GetDetaliuComandaAsync(int id) {
            return base.Channel.GetDetaliuComandaAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Imagine GetImagine(int id) {
            return base.Channel.GetImagine(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Imagine> GetImagineAsync(int id) {
            return base.Channel.GetImagineAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Material GetMaterial(int id) {
            return base.Channel.GetMaterial(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Material> GetMaterialAsync(int id) {
            return base.Channel.GetMaterialAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Mecanic GetMecanic(int id) {
            return base.Channel.GetMecanic(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Mecanic> GetMecanicAsync(int id) {
            return base.Channel.GetMecanicAsync(id);
        }
        
        public WPFCarService.WCFHostCarService.Operatie GetOperatie(int id) {
            return base.Channel.GetOperatie(id);
        }
        
        public System.Threading.Tasks.Task<WPFCarService.WCFHostCarService.Operatie> GetOperatieAsync(int id) {
            return base.Channel.GetOperatieAsync(id);
        }
        
        public void DeleteClientAutoSasiu(int idClient) {
            base.Channel.DeleteClientAutoSasiu(idClient);
        }
        
        public System.Threading.Tasks.Task DeleteClientAutoSasiuAsync(int idClient) {
            return base.Channel.DeleteClientAutoSasiuAsync(idClient);
        }
        
        public void DeleteClient(int clientId) {
            base.Channel.DeleteClient(clientId);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(int clientId) {
            return base.Channel.DeleteClientAsync(clientId);
        }
        
        public void DeleteAuto(int autoId) {
            base.Channel.DeleteAuto(autoId);
        }
        
        public System.Threading.Tasks.Task DeleteAutoAsync(int autoId) {
            return base.Channel.DeleteAutoAsync(autoId);
        }
        
        public void DeleteComanda(int comandaId) {
            base.Channel.DeleteComanda(comandaId);
        }
        
        public System.Threading.Tasks.Task DeleteComandaAsync(int comandaId) {
            return base.Channel.DeleteComandaAsync(comandaId);
        }
        
        public void DeleteMaterial(int materialId) {
            base.Channel.DeleteMaterial(materialId);
        }
        
        public System.Threading.Tasks.Task DeleteMaterialAsync(int materialId) {
            return base.Channel.DeleteMaterialAsync(materialId);
        }
        
        public void DeleteMecanic(int mecanicId) {
            base.Channel.DeleteMecanic(mecanicId);
        }
        
        public System.Threading.Tasks.Task DeleteMecanicAsync(int mecanicId) {
            return base.Channel.DeleteMecanicAsync(mecanicId);
        }
        
        public void DeleteOperatie(int operatieId) {
            base.Channel.DeleteOperatie(operatieId);
        }
        
        public System.Threading.Tasks.Task DeleteOperatieAsync(int operatieId) {
            return base.Channel.DeleteOperatieAsync(operatieId);
        }
        
        public void DeleteSasiu(int sasiuId) {
            base.Channel.DeleteSasiu(sasiuId);
        }
        
        public System.Threading.Tasks.Task DeleteSasiuAsync(int sasiuId) {
            return base.Channel.DeleteSasiuAsync(sasiuId);
        }
        
        public void DeleteDetaliuComanda(int detaliuComandaId) {
            base.Channel.DeleteDetaliuComanda(detaliuComandaId);
        }
        
        public System.Threading.Tasks.Task DeleteDetaliuComandaAsync(int detaliuComandaId) {
            return base.Channel.DeleteDetaliuComandaAsync(detaliuComandaId);
        }
        
        public void DeleteImage(int imagineId) {
            base.Channel.DeleteImage(imagineId);
        }
        
        public System.Threading.Tasks.Task DeleteImageAsync(int imagineId) {
            return base.Channel.DeleteImageAsync(imagineId);
        }
        
        public void UpdateClient(WPFCarService.WCFHostCarService.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(WPFCarService.WCFHostCarService.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public void UpdateAuto(WPFCarService.WCFHostCarService.Auto auto) {
            base.Channel.UpdateAuto(auto);
        }
        
        public System.Threading.Tasks.Task UpdateAutoAsync(WPFCarService.WCFHostCarService.Auto auto) {
            return base.Channel.UpdateAutoAsync(auto);
        }
        
        public void UpdateComanda(WPFCarService.WCFHostCarService.Comanda comanda) {
            base.Channel.UpdateComanda(comanda);
        }
        
        public System.Threading.Tasks.Task UpdateComandaAsync(WPFCarService.WCFHostCarService.Comanda comanda) {
            return base.Channel.UpdateComandaAsync(comanda);
        }
        
        public void UpdateDetaliuComanda(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda) {
            base.Channel.UpdateDetaliuComanda(detaliuComanda);
        }
        
        public System.Threading.Tasks.Task UpdateDetaliuComandaAsync(WPFCarService.WCFHostCarService.DetaliuComanda detaliuComanda) {
            return base.Channel.UpdateDetaliuComandaAsync(detaliuComanda);
        }
        
        public void UpdateImaine(WPFCarService.WCFHostCarService.Imagine imagine) {
            base.Channel.UpdateImaine(imagine);
        }
        
        public System.Threading.Tasks.Task UpdateImaineAsync(WPFCarService.WCFHostCarService.Imagine imagine) {
            return base.Channel.UpdateImaineAsync(imagine);
        }
        
        public void UpdateMaterial(WPFCarService.WCFHostCarService.Material material) {
            base.Channel.UpdateMaterial(material);
        }
        
        public System.Threading.Tasks.Task UpdateMaterialAsync(WPFCarService.WCFHostCarService.Material material) {
            return base.Channel.UpdateMaterialAsync(material);
        }
        
        public void UpdateMecanic(WPFCarService.WCFHostCarService.Mecanic mecanic) {
            base.Channel.UpdateMecanic(mecanic);
        }
        
        public System.Threading.Tasks.Task UpdateMecanicAsync(WPFCarService.WCFHostCarService.Mecanic mecanic) {
            return base.Channel.UpdateMecanicAsync(mecanic);
        }
        
        public void UpdateOperatie(WPFCarService.WCFHostCarService.Operatie operatie) {
            base.Channel.UpdateOperatie(operatie);
        }
        
        public System.Threading.Tasks.Task UpdateOperatieAsync(WPFCarService.WCFHostCarService.Operatie operatie) {
            return base.Channel.UpdateOperatieAsync(operatie);
        }
        
        public void UpdateSasiu(WPFCarService.WCFHostCarService.Sasiu sasiu) {
            base.Channel.UpdateSasiu(sasiu);
        }
        
        public System.Threading.Tasks.Task UpdateSasiuAsync(WPFCarService.WCFHostCarService.Sasiu sasiu) {
            return base.Channel.UpdateSasiuAsync(sasiu);
        }
    }
}
