//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCarService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract (IsReference = true)]
    public partial class Auto
    {
        [DataMember]
        public int AutoId { get; set; }
        [DataMember]
        public string NumarAuto { get; set; }
        [DataMember]
        public string SerieSasiu { get; set; }
        [DataMember]
        public int ClientClientId { get; set; }
        [DataMember]
        public int SasiuSasiuId { get; set; }

        [DataMember]
        public virtual Client Client { get; set; }
        [DataMember]
        public virtual Sasiu Sasiu { get; set; }
    }
}
