//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCarService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Comanda
    {
        [DataMember]
        public int ComandaId { get; set; }
        [DataMember]
        public short StareComanda { get; set; }
        [DataMember]
        public System.DateTime DataSystem { get; set; }
        [DataMember]
        public System.DateTime DataProgramare { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DataFinalizare { get; set; }
        [DataMember]
        public Nullable<int> KmBord { get; set; }
        [DataMember]
        public string Descriere { get; set; }
        [DataMember]
        public Nullable<decimal> ValoarePise { get; set; }
        [DataMember]
        public int ClientClientId { get; set; }

        [DataMember]
        public virtual Client Client { get; set; }
        [DataMember]
        public virtual DetaliuComanda DetaliuComanda { get; set; }
    }
}
